### PR TITLE
chore: setup monorepo

### LINKED ISSUE #2: Feature: Setup Monorepo

### PR DESCRIPTION
**Pull request by jhavej**
## Description

This PR converts the repository to monorepo/turborepo.

**TODO:**
- ~~tooling~~
- ~~`ui` package~~
- ~~`db` package~~
- ~~`nextjs` app~~
- ~~cleaning~~
- ~~fixing issues (typescript / eslint) - `pnpm lint` + `pnpm typecheck`~~

## What type of PR is this? (check all applicable)

- [ ] 💡 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [x] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings

https://github.com/Codehagen/Dingify/assets/9072750/5db81880-dbb1-41b2-bee6-badbab459ba5

## Steps to QA

1. Clean the repository - run `pnpm clean:workspaces` from the root
2. Install dependencies - run `pnpm install`
3. Run the app - run `pnpm dev` from the root
4. Test the app

## Added to documentation?

- [ ] 📜 README.md
- [ ] 🙅 no documentation needed

### CODE REVIEW

**Comment by jhavej** [comment]
https://github.com/Codehagen/Dingify/pull/14/commits/bde39c5f976bb331222858b8fb3b4cb5a08b1257 and https://github.com/Codehagen/Dingify/pull/14/commits/c1047b55073500f5d51e8af251779c80912283b5 👉 @Codehagen Christer, check out these changes - I've loosened some TS and ESLint rules (set to `warn`) so running `pnpm lint` and `pnpm typecheck` passes. However, we should focus on gradually switching these rules to `error` and fixing reported issues 😉

**Comment by jhavej** [comment]
https://github.com/Codehagen/Dingify/assets/9072750/452e9120-f534-4001-89c5-74e715b58aed

**Comment by jhavej** [comment]
These need follow-up fixes too 👇 

Screenshot 2024-05-12 at 21 25 45
Screenshot 2024-05-12 at 21 26 11

**Comment by jhavej** [comment]
https://github.com/Codehagen/Dingify/pull/14/commits/e57c0d91a665e1b94da2673af9f7178f8e80f9c0 seems like Inter is back 😄 

Screenshot 2024-05-12 at 21 42 17

**Review by Codehagen — APPROVED** [review]
Looks good to me ✨
Mergin this inn tomorrow on Vercel etc ⚡

**Pull request merged**
